### ISSUE TITLE
[Feature] 3.0.0 Roadmap

### ISSUE THREAD

**Issue by eneim** [eneim/toro#135]
Regarding current issues and requirement, I come up with the following Roadmap, which will define my workload for next update of Toro. New feature can be added regarding the discussion result.

## Improvement

- [x] Scroll/Playback performance. ( #113 and related)

- [x] Demo app code base, Documentation.

- [x] Lower level VideoView (close to ExoPlayer's SimpleExoVideoView).

- [ ] Better handling Activity life-cycle

## Feature

- [ ] Multi Video playback.
